
# -- Aspect based sentiment analysis (!)

http://www.anthology.aclweb.org/S/S16/S16-1044.pdf
http://www.aclweb.org/anthology/S14-2#page=858

"a composite method based on ensemble modelling combined with rich linguistic features including lexical semantic information and syntactico-semantic dependencies to address aspect based category and polarity classification."

http://alt.qcri.org/semeval2016/task5/

Deep Learning for Aspect-Based Sentiment Analysis
https://www.google.nl/url?sa=t&rct=j&q
=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjjq4O6wrrQAhVJ1hQKHeDGCNAQFggpMAE&url=https%3A%2F%2Fcs224d.stanford.edu%2Freports%2FWangBo.pdf&usg=AFQjCNG46nX42eDVpKQIstbeTH8szJ8hBw&sig2=Bx00CjssCLaNG6VXq8_bDg

http://www.datasciencecentral.com/profiles/blogs/test?xg_source=activity

# -- Sentiment for bias discovery

http://www.kdnuggets.com/2016/10/emotion-analytics-why-important.html
http://www.kdnuggets.com/2016/07/mining-twitter-data-python-part-6.html
http://www.kdnuggets.com/2016/09/slangsd-sentiment-dictionary-slang-words.html
http://www.kdnuggets.com/2016/09/trump-phenomenon-twitter-based-recount.html
http://www.kdnuggets.com/2015/10/aspect-based-sentiment-analysis-competition.html

Data/examples:

https://www.kaggle.com/crowdflower/twitter-airline-sentiment
https://www.kaggle.com/benhamner/d/crowdflower/twitter-airline-sentiment/
exploring-airline-twitter-sentiment-data


# General Sentiment:

http://www.datasciencecentral.com/profiles/blogs/test 
www.datasciencecentral.com/profiles/blogs/sentiment-analysis-of-movie-reviews-2-word2vec?xg_source=activity
www.datasciencecentral.com/profiles/blogs/opinion-mining-sentiment-analysis-and-beyond

# CSI - consumer sentiment index

http://businessoverbroadway.com/in-a-word-the-customer-sentiment-index
https://en.wikipedia.org/wiki/University_of_Michigan_Consumer_Sentiment_Index
http://businessoverbroadway.com/in-a-word-the-customer-sentiment-index
http://businessoverbroadway.com/development-of-the-customer-sentiment-index-reliability-validity-and-usefulness
http://businessoverbroadway.com/author/bobhayes/page/2  


# - Paste from https://spacy.io/

[1] https://www.semanticscholar.org/paper/0793694f7934b2fc466f4e1c0cac73546de90a8d
[2] https://www.semanticscholar.org/paper/03f21d78ead4ebbf0bcff034a501e175afe31148
[3] https://www.cs.cornell.edu/information/news/newsitem1621/yoav-artzi-wins-best-paper-award-emnlp-2015
[4] https://www.semanticscholar.org/paper/66d53083118311aaa6115d3ee666fe4ded9040d5
[5] http://www.smh.com.au/zoom
[6] https://www.semanticscholar.org/paper/9cb664c96a56869c96fcafab8dedc30c67207913
[7] https://www.semanticscholar.org/paper/09bdb61dd46f0a91dba1e6f128b84619ee30928a
[8] https://www.semanticscholar.org/paper/4094cee47ade13b77b5ab4d2e6cb9dd2b8a2917c
[9] http://spacy.io/blog/part-of-speech-POS-tagger-in-python/
[10] http://spacy.io/blog/parsing-english-in-python/

